name: Analyze Dependents

on: [pull_request]

jobs:
  analyze-dependents:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Checkout ecommerce
      uses: actions/checkout@v2
      with:
        repository: edx/frontend-app-ecommerce
        path: dependent-projects/frontend-app-ecommerce
    - name: Checkout profile
      uses: actions/checkout@v2
      with:
        repository: edx/frontend-app-profile
        path: dependent-projects/frontend-app-profile
    - name: Install dependencies
      run: npm ci
      working-directory: dependents-usage-analysis
    - name: Analyze projects
      run: npm run analyze "${GITHUB_WORKSPACE}/dependent-projects" -- --out "${GITHUB_WORKSPACE}/dependents-usage-analysis.json"
      working-directory: dependents-usage-analysis
    - name: Upload analysis output
      uses: actions/upload-artifact@v2
      with:
        name: dependents-usage-analysis-json
        path: dependents-usage-analysis.json
  commit-dependents-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Download analysis output
      uses: actions/download-artifact@v2
      with:
        name: dependents-usage-analysis-json
    - name: Check for changes
      run: |
        if !(git diff --exit-code)
        then
          echo "There is a change to the analysis output. Commit the change."
          git commit -m "docs(generated): update dependents analysis"
          # git push
        else
          echo "No significant changes. Do nothing."
        fi
        git diff
